# Generated by Django 5.0.3 on 2024-04-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreg',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
